
[project]
name = "symmer"
version = "0.0.10"
description = " An efficient Python-based framework for implementing qubit subspace methods, reducing the resource requirements for near-term quantum simulations."
authors = [
    {name="AlexisRalli", email="rallilex@hotmail.co.uk"},
    {name="Tim Weaving", email="weaving.timothy@gmail.com"},
]
requires-python = ">=3.11, <4"
license = "MIT"
dependencies = [
    "cirq-core>=1.6.1",
    "ncon>=2.0.0",
    "numba>=0.63.1",
    "openfermion>=1.7.1",
    "opt-einsum>=3.4.0",
    "qiskit>=2.3.0",
    "quimb>=1.12.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "myst-nb>=1.3.0",
    "pre-commit>=4.5.1",
    "pydocstyle>=6.3.0",
    "pytest>=9.0.2",
    "pytest-xdist>=3.8.0",
    "ruff>=0.14.13",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.7.0",
]


[tool.ruff]
exclude = ["docs/", "tests/"]
line-length = 88
indent-width = 4

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9",
    "F",
    "D", #pydocstyle
    "I", #isort
]
ignore = ["E741"]
