name: Continuous_Integration
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.14"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          python-version: ${{matrix.python-version}}
          version: "0.7.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install Dependencies
        run: |
          uv venv .venv/
          uv pip install -r pyproject.toml --all-extras
      - name: Run Pytest
        run: uv run pytest
      - name: Check Pre-commits
        run: |
          uv run pre-commit install
          uv run pre-commit run -a
        continue-on-error: true
